repos:
  - repo: local
    hooks: 
      - id: check-utf8
        name: Check files for valid UTF-8
        entry: python check_utf8.py
        language: python
        files: \.(java|html|xml|json|md|properties|yml|yaml|txt)$

      