@startuml name
left to right direction

actor User

rectangle Strava-Plus {
  package "Registrationsverfahren" {
    'user
    (Sich registrieren) ..> (Daten angeben) : <<include>>
    (Daten angeben) ..> (Registrationsseite aufrufen) : <<include>>
   }  
}
User "1" -- "1" (Sich registrieren)
@enduml