@startuml name
left to right direction

actor User

rectangle Strava-Plus {

package "Trainingsdatei bearbeiten" {
  'user
  (Trainingsdatei zur Analyse schicken) ..> (Traininsseite aufrufen) : <<include>>
  }  
}

User "1" -- "0..*" (Trainingsdatei zur Analyse schicken)

@enduml