@startuml name
left to right direction

skinparam packageStyle rectangle
skinparam shadowing false
skinparam actorStyle stickman

actor User
actor frontend
actor Server
actor backend

rectangle Strava-Plus {

  (auf die Abzeichnungsseite gehen)
  (auf die Wikiseite gehen)
  (auf die Registrierungsseite gehen)
  (auf die Logibseite gehen)
package "Trainingsseite" {
    'user
    (auf die Trainingsseite gehen) 

    'frontend
    (Trainingsseite anzeigen 'frontend') ..> (Anfrage an den Server senden) : include
    (Anfrage an den Server senden) ..> (Kartendaten vom Server bekommen) : include
    (Kartendaten vom Server bekommen) ..> (Karte darstellen) : include
    
    'server
    (Trainingsseite anzeigen 'Server') ..> (Anfrage vom frontend bekommen) : include
    (Anfrage vom frontend bekommen) ..> (Kartendaten an Frontend senden) : <<include>>
  }  

package "Challengeseite" {
    package "challengeseite laden" {
    'user
    (auf die Challengeseite gehen)

    'seite laden
    (Challengeseite anzeigen 'frontend') ..> (Anfrage an den Server 'Challengeseite' senden) : include
    (Anfкage an den Server 'Challengeseite' senden) ..> (Daten über Challenges vom Server bekommen) : include
    (Daten über Challenges vom Server bekommen) ..> (Daten in passende Form darstellen) : include

    'seite laden
    (Challengeseite anzeigen 'server') ..> (Anfrage vom frontend bekomen) : <<include>>
    (Anfrage vom frontend bekomen) ..> (Anfrage an DB senden) : <<include>>
    (Anfrage an DB senden) ..> (Daten von der DB für bestimmten Nutzer bekommen) : <<include>>
    (Daten von der DB bekommen) ..> (Daten an den frontend senden) : <<include>>

    }
    package "teilnehmen" {
        (beim Challenge teilnehmen) ..> (auf den Knopf 'beim challenge teilnehmen' drücken)

        'frontend
        'user für challenge registrieren
        (den user beim challenge registrieren 'frontend') ..> (frontend wartet auf den Klick auf Knopf) : <<extend>>
        note on link
            <i>condition:</i>
            {User drückte den Knopf}
            <i>extension point:</i>
            User drückt den Knopf
        end note
        'prüfung zur anmeldung einfügen
        (den User beim challenge registrieren) ..> (Anfrage an den Server senden) : <<include>>
        (Anfrage an den Server senden) ..> (neu Daten und Antwort von Server bekommen) : <<include>>
        (neu Daten und Antwort von Server bekommen) ..> (neu Daten darstellen und dem User sagen, dass er teilnimmt) : <<include>>


        'Server
        'user für challenge registrieren
        (den user beim challenge registrieren 'server') ..> (Anfrage vom frontend bekommen) : <<include>>
        (Anfrage vom frontend bekommen) ..> (Anfrage an backend zur Wechselung der users Status) : <<include>>
        (Anfrage an backend zur Wechselung der users Status) ..> (Antwort von backend bekommen) : <<include>>
        (Antwort von backend bekommen) ..> (Antwort und neu Daten an den frontend senden) : <<include>>

        'backend
        (Anfrage vom server bekommen) ..> (status des users in DB wechseln) : <<include>>
        (status des users in DB wechseln) ..> (antwort an den server senden) : <<include>>
    }
    }
}
User -- (auf die Trainingsseite gehen)
User -- (auf die Challengeseite gehen)

User -- (auf die Abzeichnungsseite gehen)
User -- (auf die Wikiseite gehen)
User -- (auf die Registrierungsseite gehen)
User -- (auf die Logibseite gehen)

frontend -- (Trainingsseite anzeigen 'frontend')
frontend -- (Challengeseite anzeigen 'frontend')
frontend -- (den user beim challenge registrieren 'frontend')

Server -- (Trainingsseite anzeigen 'Server')
Server -- (Challengeseite anzeigen 'server')
Server -- (den user beim challenge registrieren 'server')

backend -- (Anfrage vom server bekommen)
@enduml