@startuml name
left to right direction

' --- AKTEURE LINKS ---
actor User


rectangle Strava-Plus {
  (Abzeichnungen ansehen)
  package challenge {
    (Challenges ansehen)
    (beim challenge mitmachen)
  }
  
  (sich anmelden)
  (Trainingsdatei zur Analyse schicken)
  package Profile {
    (Profildaten angucken)
    (Profildaten ändern)
  }
  
  (sich registrieren)
  (FAQ ansehen)

}
User "1..*" --- "1 ..*" (Abzeichnungen ansehen)
User "1..*" --- "1..*" (Challenges ansehen)
User "0..*" --- "0..*" (beim challenge mitmachen)
User "1" --- "0..*" (sich anmelden)
User "1" --- "0..*" (Trainingsdatei zur Analyse schicken)
User "1..*" --- "1" (Profildaten angucken)
User "1..*" --- "1..*" (Profildaten ändern)
User "1" --- "1" (sich registrieren)
User "1..*" --- "1..*" (FAQ ansehen)

@enduml